### PR TITLE
Make this a wordpress plugin for composer

### PR DESCRIPTION
**Pull request by ravloony**
As discussed, making this a wordpress plugin, plus removing the lock file. 

Saves you a few minutes.

### CODE REVIEW

**Comment by doekenorg** [comment]
Merged in. Thanks. I believe this also helps with [bedrock](https://roots.io/bedrock/), right?

**Comment by ravloony** [comment]
Right. As you can see here: https://github.com/roots/bedrock/blob/master/composer.json#L47 the bedrock project declares paths for different plugin types.

**Comment by doekenorg** [comment]
Great. Because this was also one of the things I wanted to do, but hadn't looked into yet. So this helps 👍

**Comment by doekenorg** [comment]
@ravloony just a heads up, but I've updated the composer file, to rename the package more aptly. You can now just use https://packagist.org/packages/doekenorg/gf-entries-in-excel in your project.

**Pull request merged**
