### PR TITLE
Port to PHPSpreadsheet

### PR DESCRIPTION
**Pull request by ravloony**
We are now using this at our company, so we have done the initial port to use phpspreadsheet.

It is currently untested, I will update this PR if we find and fix any issues.

I don't know why you are committing the lockfile, as this is a library, but I have done so too, to respect your dev process.

### CODE REVIEW

**Comment by doekenorg** [comment]
Also,  you are right about the lock-file. Default project settings.  Will remove.

**Comment by ravloony** [comment]
Ok great! Glad I could help, it looks like the library will be of help to us.

Would it be ok to also update the composer file to use the "wordpress-plugin" type, and require "composer/installers" ? (see https://github.com/composer/installers for more details).

**Comment by ravloony** [comment]
Merged in the changes to master, and made the version number 1.2.4

**Comment by doekenorg** [comment]
With a little hickup in the deployment to wordpress, but version 1.2.4 is out. Thanks again. Credits in the changelog!.

**Pull request merged**
