### PR TITLE
Added ob_end_clean(), for cleaning buffer for preventing file corruption

### PR DESCRIPTION
**Pull request by sgregori**
Corruption detected saving XLSX files, and solved with this simple fix.

### CODE REVIEW

**Comment by doekenorg** [comment]
Awesome! I learned about this recently, and was planning to add this to 1.6.0. But I completely forget! Thanks man! 🙌

**Comment by sgregori** [comment]
Thank you very much for the feedback!

I give you another present:

image

Added a new feature, for enabling a little more of security.

Regards!

**Comment by doekenorg** [comment]
HI @sgregori , 

Thanks for sharing this with me. To be honest, I'm not sure if this is the approach I want to take with the plugin. I get the idea you're providing, and I think it's a valid addition; so thank you for that!

I'm just not sure if this is my preferred solution. I've been thinking about adding an internal download link for users next to the public one, so that should be kind of the same thing. The current security is only as bad as the guy who hands out that url 😉 . Also I'd like to add roles in to the mix, so not every user can download, only with a specific role.

As a side note; the `Renderer` should not be responsible for denying access. This is the job of `GFExcelOutput`. 

Let me think about this for a while. Will merge the buffer-cleaning though, and release it in 1.6.1. Thank you so much for your code and suggestion!

**Comment by sgregori** [comment]
Dont worry man, 

I added the function because was useful for our deploy, and its improvised while I learning wordpress coding.

A role based permission would be nice for us, but at this moment its right for me.

`As a side note; the Renderer should not be responsible for denying access. This is the job of GFExcelOutput.`

Right, i did it too fast and just hacking the code ;)

Thanks for your feedback. 

Regards from Spain.

**Comment by doekenorg** [comment]
Closing for now. Have merged relevant commits into my next release branch. Thanks again!

**Comment by sgregori** [comment]
Thanks , Regards!

**Comment by sgregori** [comment]
https://github.com/sgregori/gf-entries-in-excel/commit/7648a0eaf66d33aaa9e36a0fdf407ba04db825c1

Hi, another bugfix, but my repository isnt updated with yours, and today i dont have more time ;)

Regards,

**Comment by doekenorg** [comment]
Hi @sgregori, 

I actually had someone else point me towards a multibyte substr issue, which i fixed; not sure if it will also fix your issue. Maybe you can try it out for me? The problem was that multibyte strings could be cut in half. Wondering if that was your issue too. 

could you try this instead: 

```php
 $worksheet_title = mb_substr(gf_apply_filters(
            [
                'gfexcel_renderer_worksheet_title',
                $form['id'],
            ],
            $form_title,
            $form
        ), 0, Worksheet::SHEET_TITLE_MAXIMUM_LENGTH, 'utf-8');
```

Please let me know if this works instead of your fix.

**Pull request closed without merging**
